'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace FxNTPrints

    Partial Public Class Entities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=Entities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Prints() As DbSet(Of Print)
        Public Overridable Property PrintGroups() As DbSet(Of PrintGroup)
        Public Overridable Property PrintToPrintGroups() As DbSet(Of PrintToPrintGroup)
        Public Overridable Property InputControls() As DbSet(Of InputControl)
        Public Overridable Property PrintToInputControls() As DbSet(Of PrintToInputControl)
    
    End Class

End Namespace
