'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FxNTPrints

    Partial Public Class PrintGroup
        Public Property GUID As System.Guid
        Public Property Name As String = ""
        Public Property TreeFoldername As String = ""
        Public Property TreeFolderImageClose As String = ""
        Public Property TreeFolderImageOpen As String = ""
        Public Property SortId As Integer = 0
        Public Property CreatorGUID As System.Guid
        Public Property Created As Date
        Public Property LastModified As Date
        Public Property ModifierGUID As System.Guid
        Public Property IsNotVisible As Boolean
        Public Property Deleted As Date
        Public Property DeleterGUID As System.Guid
        Public Property CanNotDelete As Boolean
        Public Property Rowversion As Byte()
    
        Public Overridable Property Prints As ICollection(Of PrintToPrintGroup) = New HashSet(Of PrintToPrintGroup)
    
    End Class

End Namespace
