'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FxNTPrints

    Partial Public Class Print
        Public Property GUID As System.Guid
        Public Property Name As String = ""
        Public Property JSPrintPath As String = ""
        Public Property IsSystemReport As Boolean = false
        Public Property CreatorGUID As System.Guid
        Public Property Created As Date
        Public Property LastModified As Date
        Public Property ModifierGUID As System.Guid
        Public Property IsNotVisible As Boolean
        Public Property Deleted As Date
        Public Property DeleterGUID As System.Guid
        Public Property CanNotDelete As Boolean
        Public Property Rowversion As Byte()
    
        Public Overridable Property PrintGroups As ICollection(Of PrintToPrintGroup) = New HashSet(Of PrintToPrintGroup)
        Public Overridable Property InputControls As ICollection(Of PrintToInputControl) = New HashSet(Of PrintToInputControl)
    
    End Class

End Namespace
