'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FxNTUsers

    Partial Public Class User
        Public Property GUID As System.Guid
        Public Property Name As String = ""
        Public Property DisplayName As String = ""
        Public Property PasswordHASH As Byte()
        Public Property Description As String = ""
        Public Property DomainUser As String = ""
        Public Property IsLocked As Boolean = false
        Public Property IsNotActive As Boolean = false
        Public Property ChangePassword As Boolean = false
        Public Property LoginAttempts As Integer = 0
        Public Property LastLogin As Date = New DateTime(599266080000000000, DateTimeKind.Unspecified)
        Public Property CreatorGUID As System.Guid
        Public Property Created As Date
        Public Property LastModified As Date
        Public Property ModifierGUID As System.Guid
        Public Property IsDeleted As Boolean
        Public Property Deleted As Date
        Public Property DeleterGUID As System.Guid
        Public Property IsNotVisible As Boolean
        Public Property CanNotDelete As Boolean
        Public Property Rowversion As Byte()
    
        Public Overridable Property UserGroups As ICollection(Of UserToUserGroup) = New HashSet(Of UserToUserGroup)
    
    End Class

End Namespace
