'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FxNTMessages

    Partial Public Class Message
        Public Property GUID As System.Guid
        Public Property MessageCreated As Date = New DateTime(599266080000000000, DateTimeKind.Unspecified)
        Public Property [Class] As System.Guid = New Guid("00000000-0000-0000-0000-012000000000")
        Public Property Type As System.Guid = New Guid("00000000-0000-0000-0000-011000000000")
        Public Property From As String = ""
        Public Property [To] As String = ""
        Public Property FromName As String = ""
        Public Property ToName As String = ""
        Public Property Content As String = ""
        Public Property CreatorGUID As System.Guid
        Public Property Created As Date
        Public Property LastModified As Date
        Public Property ModifierGUID As System.Guid
        Public Property Deleted As Date
        Public Property DeleterGUID As System.Guid
        Public Property IsNotVisible As Boolean
        Public Property CanNotDelete As Boolean
        Public Property Rowversion As Byte()
    
    End Class

End Namespace
