'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FxNTAutomations

    Partial Public Class AutomationsExecution
        Public Property GUID As System.Guid
        Public Property AutomationGUID As System.Guid
        Public Property ExecutionTime As Date = New DateTime(599266080000000000, DateTimeKind.Unspecified)
        Public Property ExecutionStatus As String = ""
        Public Property IsCronExecution As Boolean = false
        Public Property CreatorGUID As System.Guid
        Public Property Created As Date
        Public Property LastModified As Date
        Public Property ModifierGUID As System.Guid
        Public Property Deleted As Date
        Public Property DeleterGUID As System.Guid
        Public Property IsNotVisible As Boolean
        Public Property CanNotDelete As Boolean
        Public Property Rowversion As Byte()
    
        Public Overridable Property Automation As Automation
    
    End Class

End Namespace
