'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FxNTAutomations

    Partial Public Class FxNTGroupList
        Public Property GUID As System.Guid
        Public Property GroupListName As String
        Public Property GroupListDescription As String
        Public Property GroupListValue As String
        Public Property GroupListValueDescription As String
        Public Property IsFXSystem As Boolean
        Public Property CreatorGUID As System.Guid
        Public Property Created As Date
        Public Property LastModified As Date
        Public Property ModifierGUID As System.Guid
        Public Property IsDeleted As Boolean
        Public Property Deleted As Date
        Public Property DeleterGUID As System.Guid
        Public Property IsNotVisible As Boolean
        Public Property CanNotDelete As Boolean
        Public Property Rowversion As Byte()
    
        Public Overridable Property Automations As ICollection(Of Automation) = New HashSet(Of Automation)
    
    End Class

End Namespace
