'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FxNTCheckLists

    Partial Public Class CheckListsStep
        Public Property GUID As System.Guid
        Public Property CheckListGuid As Nullable(Of System.Guid)
        Public Property Position As Integer = 1
        Public Property Name As String = ""
        Public Property Description As String = ""
        Public Property AutomationEntryPointAssembly As String = "MYKEY.CongAdminNT.Common.dll"
        Public Property AutomationCommand As String = ""
        Public Property Remark As String = ""
        Public Property DateFinished As Date = New DateTime(599266080000000000, DateTimeKind.Unspecified)
        Public Property CreatorGUID As System.Guid
        Public Property Created As Date
        Public Property LastModified As Date
        Public Property ModifierGUID As System.Guid
        Public Property Deleted As Date
        Public Property DeleterGUID As System.Guid
        Public Property IsNotVisible As Boolean
        Public Property CanNotDelete As Boolean
        Public Property Rowversion As Byte()
    
        Public Overridable Property CheckList As CheckList
    
    End Class

End Namespace
